apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oficina
resources:
  - ../../base
  - namespace.yaml
images:
  - name: fiapsoatgrupo36/quote-service
    newName: fiapsoatgrupo36/quote-service
    newTag: latest
patches:
  - path: patch-deployment.yaml
