apiVersion: v1
kind: Service
metadata:
  name: quote-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: quote-service
  ports:
    - name: http
      port: 8085
      targetPort: http
